#!/bin/bash

set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
    echo "Run sudo xdg-settings set default-web-browser glide.desktop && sudo update-alternatives --config x-www-browser to set glide as your default browser."
    ln -sf /opt/glide/glide /usr/bin/glide
fi

